In [2]:
import numpy as np
# Matrix A 
A = np.array([[1, 2, 3], [2, 4, 6], [4, 8, 12]])
B = np.array([5,7,9]) # Row B
print("Length of A:", len(A))


Length of A: 3


In [3]:
C = np.vstack([A, B])  # A,B to create C
print("Matrix C:\n", C)

Matrix C:
 [[ 1  2  3]
 [ 2  4  6]
 [ 4  8 12]
 [ 5  7  9]]


In [4]:
# Create D from rows 2, 3, 4 and columns 3, 4 of C
D = C[1:4, 1:3]  
print("Matrix D:\n", D)

Matrix D:
 [[ 4  6]
 [ 8 12]
 [ 7  9]]


In [5]:
# Transpose D to create E
E = D.T
print("Matrix E:\n", E)

# Check the size of E
print("Size of E:", E.shape)

Matrix E:
 [[ 4  8  7]
 [ 6 12  9]]
Size of E: (2, 3)


In [6]:
# Equally spaced vectors
v = np.linspace(1, 10, 5)  
print("Equally spaced vector:", v)

Equally spaced vector: [ 1.    3.25  5.5   7.75 10.  ]


In [7]:
# max and min in each column of A
print("Max in each column of A:", np.max(A, axis=0))
print("Min in each column of A:", np.min(A, axis=0))

# max and min in each row of A
print("Max in each row of A:", np.max(A, axis=1))
print("Min in each row of A:", np.min(A, axis=1))

# mean and sum in each column and row of A
print("Mean of each column in A:", np.mean(A, axis=0))
print("Sum of each row in A:", np.sum(A, axis=1))

Max in each column of A: [ 4  8 12]
Min in each column of A: [1 2 3]
Max in each row of A: [ 3  6 12]
Min in each row of A: [1 2 4]
Mean of each column in A: [2.33333333 4.66666667 7.        ]
Sum of each row in A: [ 6 12 24]


In [8]:
# random matrices F and G
F = np.random.randint(1, 100, (3, 3))
print("Matrix F:\n", F)

G = np.random.randint(1, 100, (3, 3))
print("Matrix G:\n", G)

Matrix F:
 [[84 92 36]
 [44 77 78]
 [10 79 28]]
Matrix G:
 [[31 79  4]
 [94 69 27]
 [11 40 27]]


In [9]:
# perform scalar multiplication, addition, subtraction, and element-wise multiplication
print("F * 2:\n", F * 2)  # Scalar multiplication
print("F + G:\n", F + G)  # Matrix addition
print("F - G:\n", F - G)  # Matrix subtraction
print("Element-wise multiplication\n", np.multiply(F, G))

F * 2:
 [[168 184  72]
 [ 88 154 156]
 [ 20 158  56]]
F + G:
 [[115 171  40]
 [138 146 105]
 [ 21 119  55]]
F - G:
 [[ 53  13  32]
 [-50   8  51]
 [ -1  39   1]]
Element-wise multiplication
 [[2604 7268  144]
 [4136 5313 2106]
 [ 110 3160  756]]


In [10]:
# size of F and A, then perform matrix multiplication if compatible
if F.shape[1] == A.shape[0]:  
    print("Matrix Multiplication:\n", np.dot(F, A))

Matrix Multiplication:
 [[ 412  824 1236]
 [ 510 1020 1530]
 [ 280  560  840]]


In [11]:
# special matrices
identity_matrix = np.eye(3)  # 3x3 identity matrix
print("Identity Matrix:\n", identity_matrix)

zero_matrix = np.zeros((5, 3))  # 5x3 zero matrix
print("Zero Matrix:\n", zero_matrix)

one_matrix = np.ones((4, 2))  # 4x2 matrix of ones
print("One Matrix:\n", one_matrix)

diagonal_matrix = np.diag([1, 2, 7])  # Diagonal matrix
print("Diagonal Matrix:\n", diagonal_matrix)

random_matrix = np.random.randint(10, 100, (6, 6))  # 6x6 random matrix
extracted_diagonal = np.diag(random_matrix)  # Extract diagonal elements
print("Extracted Diagonal Elements:\n", extracted_diagonal)

sparse_diag_matrix = np.diag([1, 2, 3, 4])  # Sparse diagonal matrix
dense_matrix = sparse_diag_matrix.astype(float)  
print("Dense Matrix:\n", dense_matrix)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
One Matrix:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 7]]
Extracted Diagonal Elements:
 [41 68 48 21 64 56]
Dense Matrix:
 [[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]
